Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2017
Var
// Seção de Declarações das variáveis 

resultado: real
n: inteiro

var_passo: real;
Inicio
   para n de -1 ate 100 passo 1 faca
       var_passo <- 0.10
       resultado <- (n / 10)

        escreva(resultado)
   fimpara
   

Fimalgoritmo